### ISSUE TITLE
A probable BUG at fetch stage.

### ISSUE THREAD

**Issue by KLSQR** [ultraembedded/riscv#1]
For version 5ce4718.
The module "riscv_fetch" in RV32I core reads instruction from ICache, it feds "fetch_instr_o" and "fetch_pc_o" to "riscv_decode" module. The "fetch_pc_o" is registered for one clock cycle, but "fetch_instr_o" is not. Thus, the pc and instruction seen by the decoder do not match.

This probably won't cause errors when the core executes algorithm and memory instruction. But after executing branch instruction like "JALR", the first instruction of the branched address is ignored by the core, which causes core function error.

**Comment by ultraembedded** [comment]
This is intentional and not a bug.

The instruction fetch memory, which could be a tightly coupled memory (TCM) or from an instruction cache, is going to take 1 or more cycles to produce the instruction (on icache_inst_i), as these types of memories are not feasibly implemented with memories with asynchronous read outputs.

For this reason, fetch_pc_o is registered, so that it matches icache_inst_i->fetch_instr_o.
